### ISSUE TITLE
Text unwanted

### ISSUE THREAD

**Issue by Karnak19** [Karnak19/WoW-Search-Engine#13]
Un petit bug sur Master, à résoudre rapidement !
Du texte non voulu. Potentiellement un commentaire mal commenté ?

![image](https://user-images.githubusercontent.com/7700494/56734622-a76ef200-6763-11e9-8b6f-23bf2e98e498.png)

Comment résoudre de bug ? 

1. Tirer une branche avec le nom de l'issue depuis master
2. Résoudre le bug
3. Push la branche sur Github, puis faire une Pull Request vers Dev (puis vers Master)

**Comment by Zesysy** [comment]
Bug résolu sur le commit 1d0d9ca de raid_progression
